/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import service.PedidoService;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class ListaPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaPedidos
     */
    public ListaPedidos() {
        initComponents();
        jTextField1.setEnabled(false);
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        DefaultTableModel tm = new DefaultTableModel();
        jTable1.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Pesquisa de pedidos");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title d1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo de pesquisa...", "Buscar todos os pedidos", "ID", "Data de entrada", "Intervalo de datas", "Tipo de Serviço", "Placa" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Parâmetros de pesquisa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregaModel(List<Vector> pedidos) {
        DefaultTableModel tm = new DefaultTableModel();
        tm.addColumn("Id");
        tm.addColumn("Data de Entrada");
        tm.addColumn("Tipo de serviço");
        tm.addColumn("Valor");
        tm.addColumn("Placa");
        jTable1.setModel(tm);
        for (Vector vector : pedidos) {
            tm.addRow(vector);
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PedidoService pService = new PedidoService();
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(this, "Selecione o tipo de pesquisa");
                break;
            case 1:

                List<Vector> pedidos = pService.buscaTodosPedidosVec();
                carregaModel(pedidos);
                if (pedidos.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Busca concluida, sem resultadoss");
                } else {
                    JOptionPane.showMessageDialog(this, "Busca concluida");
                }
                break;
            case 2:
                if (!jTextField1.getText().equals("")) {
                    pedidos = pService.buscaPedidosIdVec(jTextField1.getText());
                    carregaModel(pedidos);
                    if (pedidos.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Busca concluida, sem resultados");
                    } else {
                        JOptionPane.showMessageDialog(this, "Busca concluida");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Campo vazio");
                }
                break;
            case 3:
                Calendar data1 = jDateChooser1.getCalendar();
                if (data1 == null) {
                    JOptionPane.showMessageDialog(this, "Campo Vazio");
                } else {
                    pedidos = pService.buscaPedidosDataVec(jDateChooser1.getCalendar());
                    carregaModel(pedidos);
                    if (pedidos.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Busca concluida, sem retornos");
                    } else {
                        JOptionPane.showMessageDialog(this, "Busca concluida");
                    }
                }
                break;
            case 4:
                data1 = jDateChooser1.getCalendar();
                Calendar data2 = jDateChooser2.getCalendar();
                if (data1 == null || data2 == null) {
                    JOptionPane.showMessageDialog(this, "1 ou mais campos estão vazios");
                } else {
                    if (jDateChooser1.getCalendar().getTimeInMillis() > jDateChooser2.getCalendar().getTimeInMillis()) {
                        JOptionPane.showMessageDialog(this, "A data inicial deve ser menor que a data final", "Erro", 0);
                    } else {
                        pedidos = pService.buscaPedidosDatasVec(jDateChooser1.getCalendar(), jDateChooser2.getCalendar());
                        carregaModel(pedidos);
                        if (pedidos.isEmpty()) {
                            JOptionPane.showMessageDialog(this, "Busca concluida, sem resultados");
                        } else {
                            JOptionPane.showMessageDialog(this, "Busca concluida");
                        }
                    }
                }
                break;
            case 5:
                if (!jTextField1.getText().equals("")) {
                    pedidos = pService.buscaPedidosTipoVec(jTextField1.getText());
                    carregaModel(pedidos);
                    if (pedidos.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Busca concluida, sem resultados");
                    } else {
                        JOptionPane.showMessageDialog(this, "Busca concluida");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Campo vazio");
                }
                break;
            case 6:
                if (!jTextField1.getText().equals("")) {
                    pedidos = pService.buscaPedidosPlacaVec(jTextField1.getText());
                    carregaModel(pedidos);
                    if (pedidos.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Busca concluida, sem resultados");
                    } else {
                        JOptionPane.showMessageDialog(this, "Busca concluida");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Campo vazio");
                }
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        switch (jComboBox1.getSelectedIndex()) {
            case 1:
                jTextField1.setEnabled(false);
                jDateChooser1.setEnabled(false);
                jDateChooser2.setEnabled(false);
                break;
            case 3:
                jTextField1.setEnabled(false);
                jDateChooser1.setEnabled(true);
                jDateChooser2.setEnabled(false);
                jLabel1.setText("Data");
                jLabel2.setText("");
                break;
            case 4:
                jTextField1.setEnabled(false);
                jDateChooser1.setEnabled(true);
                jDateChooser2.setEnabled(true);
                jLabel1.setText("Data Inicial");
                jLabel2.setText("Data Final");
                break;
            case 2:
            case 5:
            case 6:
                jTextField1.setEnabled(true);
                jDateChooser1.setEnabled(false);
                jDateChooser2.setEnabled(false);
                jLabel1.setText("");
                jLabel2.setText("");
        }

    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
